CREATE OR REPLACE TABLE DEMO_DB.REPORTING_JIHUNOH.FUNNEL_PERFORMANCE AS
SELECT 
    -- LEAD DETAILS
    l.LEAD_ID,
    l.FORM_SUBMISSION_DATE,
    l.FIRST_SALES_CALL,
    l.STATUS AS CURRENT_STATUS,
    l.LOCATION_COUNT,
    l.CUISINE_TYPES,

    -- FORM SUBMISSION TO FIRST CALL
    DATEDIFF('hour', l.FORM_SUBMISSION_DATE, l.FIRST_SALES_CALL) AS HOURS_TO_CALL,
    CASE 
        WHEN l.FORM_SUBMISSION_DATE IS NULL THEN 'Outbound'
        WHEN DATEDIFF('hour', l.FORM_SUBMISSION_DATE, l.FIRST_SALES_CALL) <= 48 THEN 'Target: Within 48 hours'
        ELSE 'Missed: Late (>48h)'
    END AS SPEED_SEGMENT,

    -- CUSTOMER TIERING
    l.PREDICTED_SALES_WITH_OWNER,
    CASE 
        WHEN l.PREDICTED_SALES_WITH_OWNER > 6000 THEN 'Tier 1 (Whale >$6k)'
        WHEN l.PREDICTED_SALES_WITH_OWNER > 4000 THEN 'Tier 2 ($4k-$6k)'
        WHEN l.PREDICTED_SALES_WITH_OWNER > 2000 THEN 'Tier 3 ($2k-$4k)'
        ELSE 'Tier 4 (<$2k)'
    END AS VALUE_TIER,

    -- MARKETPLACE & TECH
    l.MARKETPLACES_USED,
    CASE 
        WHEN (l.MARKETPLACES_USED = '[]' OR l.MARKETPLACES_USED IS NULL) THEN 0 
        ELSE REGEXP_COUNT(l.MARKETPLACES_USED, ',') + 1 
    END AS APP_COUNT,
    
    l.ONLINE_ORDERING_USED,
    CASE 
        WHEN (l.ONLINE_ORDERING_USED = '[]' OR l.ONLINE_ORDERING_USED IS NULL) THEN FALSE 
        ELSE TRUE 
    END AS HAS_EXISTING_TECH,
    CASE 
        WHEN (l.ONLINE_ORDERING_USED = '[]' OR l.ONLINE_ORDERING_USED IS NULL) THEN 0 
        ELSE REGEXP_COUNT(l.ONLINE_ORDERING_USED, ',') + 1 
    END AS ONLINE_ORDERING_APP_CNT,

    -- ACTIVITY & EFFICIENCY 
    l.SALES_CALL_COUNT,
    CASE WHEN l.SALES_CALL_COUNT > 5 THEN TRUE ELSE FALSE END AS OVER_CALL,
    
    l.SALES_EMAIL_COUNT,
    l.SALES_TEXT_COUNT,
    CASE WHEN l.SALES_TEXT_COUNT > 0 THEN TRUE ELSE FALSE END AS HAS_ENGAGED_SMS,

    -- OUTCOMES
    o.OPPORTUNITY_ID,
    o.IS_WON,
    o.CLOSE_DATE,
    o.DEMO_HELD,
    CASE 
        WHEN o.DEMO_SET_DATE IS NOT NULL AND o.DEMO_HELD = FALSE THEN 'No-Show'
        WHEN o.DEMO_SET_DATE IS NOT NULL AND o.DEMO_HELD = TRUE THEN 'Completed'
        ELSE 'No Demo Booked'
    END AS DEMO_STATUS,

    -- ARR
    (500 * 12) + (COALESCE(l.PREDICTED_SALES_WITH_OWNER, 0) * 0.05 * 12) AS POTENTIAL_LTV_1YR,
    CASE 
        WHEN o.IS_WON THEN (500 * 12) + (COALESCE(l.PREDICTED_SALES_WITH_OWNER, 0) * 0.05 * 12)
        ELSE 0 
    END AS REVENUE_WON_1YR,
    CASE 
        WHEN o.IS_WON = FALSE AND o.IS_LOST = TRUE THEN (500 * 12) + (COALESCE(l.PREDICTED_SALES_WITH_OWNER, 0) * 0.05 * 12)
        ELSE 0 
    END AS LOST_REVENUE_1YR

FROM DEMO_DB.DW_JIHUNOH.FACT_LEADS l
LEFT JOIN DEMO_DB.DW_JIHUNOH.FACT_OPPORTUNITIES o 
    ON l.CONVERTED_OPPORTUNITY_ID = o.OPPORTUNITY_ID;
